allowBuilds:
  esbuild: set this to true or false
  msw: set this to true or false
  vue-demi: set this to true or false
onlyBuiltDependencies:
  - esbuild
  - msw
  - vue-demi
verifyDepsBeforeRun: false
